const recommendations = {
    movies: [
        {
            id: "m9",
            title: "Stalker",
            subtitle: "Andrei Tarkovsky, 1979",
            image: "images/stalker.png",
            technicianReview: "Filmed in hazardous locations. The long takes induce a trance-like state, forcing the viewer to alter their breathing.",
            soulNote: "A journey into the Zone where your deepest wish is granted—and that is the most terrifying thing of all.",
            significance: "It predicts the spiritual void of the modern world and our desperate, dangerous search for meaning.",
            artistFact: "The film was actually shot twice. The first version's negatives were destroyed in a lab accident, forcing Tarkovsky to reshoot the entire movie with a lower budget.",
            layout: "featured",
            dailyContext: "\"The direct path is not the safest.\"",
        },
        {
            id: "m6",
            title: "2001: A Space Odyssey",
            subtitle: "Stanley Kubrick, 1968",
            image: "images/2001.png",
            technicianReview: "Pre-CGI visual effects that still hold up. The slit-scan technique for the Stargate sequence was revolutionary.",
            soulNote: "A cold, terrifying look at our place in the cosmos. It asks if we are the masters of our tools or their victims.",
            significance: "As AI advances, HAL 9000 becomes less of a villain and more of a prophecy.",
            artistFact: "Kubrick had the set completely destroyed after filming so the props couldn't be used in lesser sci-fi films.",
            layout: "tall",
            dailyContext: "\"I'm sorry, Dave. I'm afraid I can't do that.\"",
        },
        {
            id: "m7",
            title: "Do the Right Thing",
            subtitle: "Spike Lee, 1989",
            image: "images/do_the_right_thing.png",
            technicianReview: "The use of Dutch angles and a saturated warm color palette makes the heatwave physically palpable.",
            soulNote: "A pressure cooker of racial tension that refuses to give easy answers. It demands you pick a side.",
            significance: "Decades later, the tragedy of Radio Raheem feels like it could have been filmed yesterday on an iPhone.",
            artistFact: "Obama took Michelle to see this movie on their first date.",
            layout: "wide",
            dailyContext: "\"Always do the right thing.\"",
        },
        {
            id: "m8",
            title: "Portrait of a Lady on Fire",
            subtitle: "Céline Sciamma, 2019",
            image: "images/lady_on_fire.png",
            technicianReview: "Shot in 8K but with zero music score until the very end. The sound of the wind and fire replaces the orchestra.",
            soulNote: "A study of the female gaze. It shows love not as possession, but as the act of truly seeing someone.",
            significance: "It reclaims the muse from being an object and makes her an active participant in the creation of art.",
            artistFact: "The lead actresses were ex-lovers in real life, adding a layer of genuine history and tenderness to their performance.",
            layout: "regular",
            dailyContext: "\"Do all lovers feel they're inventing something?\"",
        },
        {
            id: "m10",
            title: "Blade Runner",
            subtitle: "Ridley Scott, 1982",
            image: "images/blade_runner.png",
            technicianReview: "The definitive Cyberpunk aesthetic. The lighting through smoke and rain created a 'future noir' look that has been copied for 40 years.",
            soulNote: "It asks what it means to be human. If a machine can love and fear death, does it have a soul?",
            significance: "As we enter the age of synthetic biology, the question of 'more human than human' is no longer fiction.",
            artistFact: "Philip K. Dick, who wrote the source novel, was so impressed by the special effects test reel that he said, 'It was my own interior world. They caught it perfectly.'",
            layout: "regular",
            dailyContext: "\"Tears in rain.\"",
        },
    ],
    music: [
        {
            id: "mu4",
            title: "A Love Supreme",
            subtitle: "John Coltrane, 1965",
            image: "images/coltrane.png",
            technicianReview: "Recorded in one session. The interplay between Elvin Jones and Coltrane is telepathic.",
            soulNote: "A spiritual ascension. It vibrates with gratitude.",
            significance: "Coltrane's unashamed declaration of gratitude to a higher power is a radical act.",
            artistFact: "Coltrane locked himself in his bedroom for five days to compose this album.",
            layout: "featured",
            dailyContext: "\"A Love Supreme. A Love Supreme.\"",
        },
        {
            id: "mu1",
            title: "Buena Vista Social Club",
            subtitle: "BVSC, 1997",
            image: "images/buena_vista.png",
            technicianReview: "Recorded in six days in Havana using vintage tube mics. The lack of separation creates a warm, communal room sound.",
            soulNote: "It proves that passion has no expiration date.",
            significance: "This album is a defiant monument to the beauty of aging.",
            artistFact: "Ibrahim Ferrer was shining shoes to make a living before being asked to record the vocals.",
            layout: "tall",
            dailyContext: "\"De Alto Cedro voy para Marcané.\"",
        },
        {
            id: "mu5",
            title: "Homogenic",
            subtitle: "Björk, 1997",
            image: "images/bjork.png",
            technicianReview: "A fusion of tectonic beats and lush strings. The distortion is deliberate.",
            soulNote: "It captures the strength of the solitary heart.",
            significance: "Björk foresaw our cyborg future. She showed us that machines and nature are not enemies but lovers.",
            artistFact: "Björk recorded vocals outside, sometimes while running, to capture raw energy.",
            layout: "wide",
            dailyContext: "\"Emotional landscapes.\"",
        },
        {
            id: "mu9",
            title: "Blue",
            subtitle: "Joni Mitchell, 1971",
            image: "images/blue.png",
            technicianReview: "Stripped back to just dulcimer and piano. The microphone placement captures every breath and lip smack.",
            soulNote: "The most honest breakup album ever made. It feels like reading someone's diary.",
            significance: "In a world of curated Instagram lives, 'Blue' dares to be messy and pathetic in the most beautiful way.",
            artistFact: "Mitchell said of this album, 'I felt like I had absolutely no secrets from the world and I couldn't pretend in my life to be strong.'",
            layout: "regular",
            dailyContext: "\"I am on a lonely road and I am traveling.\"",
        },
        {
            id: "mu8",
            title: "Kid A",
            subtitle: "Radiohead, 2000",
            image: "images/radiohead.png",
            technicianReview: "Abandoning guitars for Ondes Martenots and modular synths. It sounds like a computer trying to learn how to cry.",
            soulNote: "The soundtrack to the dissociation of the internet age. It captures the feeling of being overwhelmed by data.",
            significance: "It predicted the anxiety of the information era long before social media took over.",
            artistFact: "Thom Yorke almost quit music before this album due to severe depression and writer's block.",
            layout: "regular",
            dailyContext: "\"Everything in its right place.\"",
        },
    ],
    books: [
        {
            id: "b4",
            title: "Dune",
            subtitle: "Frank Herbert, 1965",
            image: "images/dune.png",
            technicianReview: "World-building at its finest. It's a complex system manual disguised as narrative.",
            soulNote: "It teaches us about fear. 'Fear is the mind-killer.'",
            significance: "The ultimate text on ecology and resource scarcity.",
            artistFact: "Dune was rejected by over 20 publishers before being accepted by a company that printed car repair manuals.",
            layout: "featured",
            dailyContext: "\"Fear is the mind-killer.\"",
        },
        {
            id: "b7",
            title: "The Road",
            subtitle: "Cormac McCarthy, 2006",
            image: "images/the_road.png",
            technicianReview: "Minimalist punctuation and stark prose create a landscape of absolute desolation.",
            soulNote: "A love story between a father and son at the end of the world.",
            significance: "As climate anxiety grows, this book forces us to ask what is worth saving when everything is gone.",
            artistFact: "McCarthy got the idea for the book while looking out a hotel window at night in El Paso with his sleeping son.",
            layout: "tall",
            dailyContext: "\"Carry the fire.\"",
        },
        {
            id: "b1",
            title: "God of Small Things",
            subtitle: "Arundhati Roy, 1997",
            image: "images/small_things.png",
            technicianReview: "A linguistic tour de force. Roy creates her own vocabulary to describe the indescribable.",
            soulNote: "A devastating look at how Big Things crush Small Things.",
            significance: "Roy insists on the complexity of the 'Small Things' in a polarized world.",
            artistFact: "Arundhati Roy trained as an architect before writing the novel.",
            layout: "wide",
            dailyContext: "\"Things can change in a day.\"",
        },
        {
            id: "b3",
            title: "100 Years of Solitude",
            subtitle: "G.G. Márquez, 1967",
            image: "images/solitude.png",
            technicianReview: "The definitive text of Magical Realism. The prose style mimics the cyclical nature of history.",
            soulNote: "It teaches us that time is not linear, but a circle.",
            significance: "A cautionary tale about the isolation that comes from power.",
            artistFact: "Márquez sold his car and pawned his household appliances to support his family while writing.",
            layout: "regular",
            dailyContext: "\"He really had been through death.\"",
        },
        {
            id: "b8",
            title: "Slaughterhouse-Five",
            subtitle: "Kurt Vonnegut, 1969",
            image: "images/slaughterhouse.png",
            technicianReview: "A non-linear anti-war novel that uses sci-fi tropes to process PTSD.",
            soulNote: "A resigned shrug at the absurdity of death.",
            significance: "It creates a language for trauma that traditional narrative cannot handle.",
            artistFact: "Vonnegut actually survived the firebombing of Dresden as a POW by hiding in a meat locker.",
            layout: "regular",
            dailyContext: "\"So it goes.\"",
        },
    ],
};
