const recommendations = {
    movies: [
        {
            id: "m2",
            title: "Parasite",
            subtitle: "Bong Joon-ho, 2019",
            image: "images/parasite.png",
            technicianReview: "A masterclass in blocking and set design. The entire house was built to serve the camera movements. Every frame emphasizes the vertical hierarchy of class.",
            soulNote: "It exposes the polite violence of capitalism. A thriller that leaves you laughing until you realize the joke is on all of us.",
            significance: "As the wealth gap widens globally, 'Parasite' remains the definitive cinematic text of our time.",
            artistFact: "The Parks' house was an open set built in a tank, designed based on the sun's trajectory.",
            layout: "featured",
            dailyContext: "\"It's so metaphorical.\"",
        },
        {
            id: "m5",
            title: "Mirror",
            subtitle: "Andrei Tarkovsky, 1975",
            image: "images/mirror.png",
            technicianReview: "A non-linear editing marvel. Tarkovsky creates a logic of dreams rather than narrative.",
            soulNote: "It feels like remembering a life you never lived. A poetic meditation on childhood.",
            significance: "Tarkovsky insists that the past is not dead; it is a living texture.",
            artistFact: "Tarkovsky reconstructed his childhood home from old photographs down to the exact plants in the garden.",
            layout: "tall",
            dailyContext: "\"Words can't express a person's whole vividness.\"",
        },
        {
            id: "m4",
            title: "In the Mood for Love",
            subtitle: "Wong Kar-wai, 2000",
            image: "images/in_the_mood_for_love.png",
            technicianReview: "Christopher Doyle's use of color saturation and framing creates a claustrophobic intimacy.",
            soulNote: "The most romantic film ever made where nothing happens. It captures the eternal ache of 'what if'.",
            significance: "Wong Kar-wai celebrates the agonizing beauty of restraint.",
            artistFact: "Wong Kar-wai shot so much footage that he originally planned a 4-hour epic and worked without a finished script.",
            layout: "wide",
            dailyContext: "\"That era has passed.\"",
        },
        {
            id: "m1",
            title: "Pather Panchali",
            subtitle: "Satyajit Ray, 1955",
            image: "images/pather_panchali.png",
            technicianReview: "Shot on a shoestring budget with a first-time crew. Subrata Mitra invented 'bounce lighting' for this film to mimic daylight. The visuals are raw, poetic, and texture-heavy.",
            soulNote: "A child's view of the world where poverty doesn't strip away wonder. The train scene is a timeless metaphor for the distance between dreams and reality.",
            significance: "In our era of high-speed digital consumption, Ray's masterpiece teaches us the radical act of patience. It reminds us that dignity is not a function of wealth.",
            artistFact: "Satyajit Ray pawned his wife's jewelry to fund the film. When funds ran dry, the production stopped for a year.",
            layout: "regular",
            dailyContext: "\"The train is coming! The train!\"",
        },
        {
            id: "m3",
            title: "Apocalypse Now",
            subtitle: "F.F. Coppola, 1979",
            image: "images/apocalypse_now.png",
            technicianReview: "Walter Murch invented 'Sound Design' for this film. The helicopter blades blending with the ceiling fan is the definitive example of sonic psychological transition.",
            soulNote: "It stares directly into the heart of darkness. It forces you to witness how fragile morality is when stripped of civilization.",
            significance: "Coppola's fever dream drags us back to the visceral, madness-inducing reality of conflict.",
            artistFact: "The production was a disaster. Sets were destroyed by a typhoon and Martin Sheen had a heart attack on set.",
            layout: "regular",
            dailyContext: "\"I love the smell of napalm in the morning.\"",
        },
    ],
    music: [
        {
            id: "mu7",
            title: "To Pimp a Butterfly",
            subtitle: "Kendrick Lamar, 2015",
            image: "images/kendrick.png",
            technicianReview: "A dense collage of free jazz, funk, and spoken word. The mixing is intentionally chaotic to mirror the internal conflict.",
            soulNote: "A scream of black excellence and trauma. It is therapy recorded on tape.",
            significance: "The defining protest album of the 21st century.",
            artistFact: "Kendrick originally planned to name the album 'Tu Pimp A Caterpillar' to form the acronym T.U.P.A.C.",
            layout: "featured",
            dailyContext: "\"We gon' be alright.\"",
        },
        {
            id: "mu6",
            title: "Dark Side of the Moon",
            subtitle: "Pink Floyd, 1973",
            image: "images/pink_floyd.png",
            technicianReview: "Alan Parsons used tape loops and physical editing to create seamless transitions. A benchmark for studio engineering.",
            soulNote: "A guided tour through the madness of modern life: time, money, and war.",
            significance: "It remains the ultimate album about the human condition under capitalism.",
            artistFact: "The album remained on the Billboard charts for 741 consecutive weeks—over 14 years.",
            layout: "tall",
            dailyContext: "\"There is no dark side of the moon really.\"",
        },
        {
            id: "mu2",
            title: "Sounds of India",
            subtitle: "Ravi Shankar, 1968",
            image: "images/ravi_shankar.png",
            technicianReview: "A pristine capture of complex ragas. The recording balances the sympathetic resonance of the sitar with the punch of the tabla perfectly.",
            soulNote: "Music as meditation. It doesn't follow Western verse-chorus structure but flows like a river.",
            significance: "Indian Classical music demands deep listening, the antidote to the 3-minute pop song.",
            artistFact: "Ravi Shankar famously gave George Harrison sitar lessons.",
            layout: "wide",
            dailyContext: "\"Raga is a form that cannot be separated from the divine.\"",
        },
        {
            id: "mu3",
            title: "Grace",
            subtitle: "Jeff Buckley, 1994",
            image: "images/jeff_buckley.png",
            technicianReview: "The vocal control is technically perfect, spanning four octaves. The reverb on the guitar creates a cathedral-like space.",
            soulNote: "Pure, unfiltered emotion. It sounds like a man singing for his life.",
            significance: "Buckley's raw vulnerability is startling in an era of auto-tune.",
            artistFact: "Buckley drowned during a spontaneous evening swim in the Mississippi River, fully clothed, singing Led Zeppelin.",
            layout: "regular",
            dailyContext: "\"There's the moon asking to stay.\"",
        },
        {
            id: "mu10",
            title: "Kind of Blue",
            subtitle: "Miles Davis, 1959",
            image: "images/miles.png",
            technicianReview: "Recorded with almost no rehearsal. The tape hiss is part of the atmosphere.",
            soulNote: "Coolness personified. It is the sound of 3 AM in a city that understands you.",
            significance: "It defined 'cool' for the 20th century and taught us that what you don't play is as important as what you do.",
            artistFact: "Miles gave the musicians only sketches of scales and melodies hours before recording.",
            layout: "regular",
            dailyContext: "\"So What.\"",
        },
    ],
    books: [
        {
            id: "b9",
            title: "The Handmaid's Tale",
            subtitle: "Margaret Atwood, 1985",
            image: "images/handmaid.png",
            technicianReview: "Speculative fiction that relies only on historical precedents. Nothing in the book hasn't happened somewhere before.",
            soulNote: "A terrifying warning about how quickly freedom can be traded for security.",
            significance: "It has become the primary symbol for women's rights protests globally.",
            artistFact: "Atwood wrote the book in West Berlin in 1984, hearing the sonic booms of Soviet fighter jets.",
            layout: "featured",
            dailyContext: "\"Nolite te bastardes carborundorum.\"",
        },
        {
            id: "b5",
            title: "Master and Margarita",
            subtitle: "Mikhail Bulgakov, 1967",
            image: "images/master_margarita.png",
            technicianReview: "A satirical masterpiece written in secret. The tone shifts from slapstick to biblical tragedy.",
            soulNote: "Proof that manuscripts don't burn.",
            significance: "Written under tyranny, it is a testament to the fact that truth cannot be censored forever.",
            artistFact: "Bulgakov burned the first manuscript of the novel in a stove, fearing a police raid.",
            layout: "tall",
            dailyContext: "\"Manuscripts don't burn.\"",
        },
        {
            id: "b6",
            title: "Invisible Man",
            subtitle: "Ralph Ellison, 1952",
            image: "images/invisible_man.png",
            technicianReview: "The jazz-influenced prose style shifts rhythm to match the protagonist's chaotic journey.",
            soulNote: "A harrowing look at what it means to be seen but not known.",
            significance: "It remains the essential American novel about race and identity.",
            artistFact: "Ellison spent seven years writing the novel, working on it in a friend's photography studio.",
            layout: "wide",
            dailyContext: "\"I am invisible, understand, because people refuse to see me.\"",
        },
        {
            id: "b10",
            title: "In Search of Lost Time",
            subtitle: "Marcel Proust, 1913",
            image: "images/proust.png",
            technicianReview: "The sentences are architectural marvels, designed to capture the exact texture of a fleeting thought.",
            soulNote: "The ultimate study of memory and how we construct our own reality.",
            significance: "In an age of short attention spans, Proust demands we slow down and truly notice our lives.",
            artistFact: "Proust wrote the last volumes while bedridden in a cork-lined bedroom to block out all noise.",
            layout: "regular",
            dailyContext: "\"The only true paradise is paradise lost.\"",
        },
        {
            id: "b2",
            title: "Kafka on the Shore",
            subtitle: "Haruki Murakami, 2002",
            image: "images/kafka.png",
            technicianReview: "Master of the metaphysical split-narrative. The translation captures the dream logic perfectly.",
            soulNote: "A labyrinth of the subconscious. It asks if we can escape our destiny.",
            significance: "Murakami validates our confusion in a surreal reality.",
            artistFact: "Murakami wakes up at 4:00 AM every day and writes for five to six hours.",
            layout: "regular",
            dailyContext: "\"The world is a metaphor.\"",
        },
    ],
};
