const recommendations = {
    movies: [
        {
            id: "m5",
            title: "Mirror",
            subtitle: "Andrei Tarkovsky, 1975",
            image: "images/mirror.png",
            technicianReview: "A non-linear editing marvel. Tarkovsky creates a logic of dreams rather than narrative.",
            soulNote: "It feels like remembering a life you never lived. A poetic meditation on childhood.",
            significance: "Tarkovsky insists that the past is not dead; it is a living texture.",
            artistFact: "Tarkovsky reconstructed his childhood home from old photographs down to the exact plants in the garden.",
            layout: "featured",
            dailyContext: "\"Words can't express a person's whole vividness.\"",
        },
        {
            id: "m9",
            title: "Stalker",
            subtitle: "Andrei Tarkovsky, 1979",
            image: "images/stalker.png",
            technicianReview: "Filmed in hazardous locations. The long takes induce a trance-like state, forcing the viewer to alter their breathing.",
            soulNote: "A journey into the Zone where your deepest wish is granted—and that is the most terrifying thing of all.",
            significance: "It predicts the spiritual void of the modern world and our desperate, dangerous search for meaning.",
            artistFact: "The film was actually shot twice. The first version's negatives were destroyed in a lab accident, forcing Tarkovsky to reshoot the entire movie with a lower budget.",
            layout: "tall",
            dailyContext: "\"The direct path is not the safest.\"",
        },
        {
            id: "m1",
            title: "Pather Panchali",
            subtitle: "Satyajit Ray, 1955",
            image: "images/pather_panchali.png",
            technicianReview: "Shot on a shoestring budget with a first-time crew. Subrata Mitra invented 'bounce lighting' for this film to mimic daylight. The visuals are raw, poetic, and texture-heavy.",
            soulNote: "A child's view of the world where poverty doesn't strip away wonder. The train scene is a timeless metaphor for the distance between dreams and reality.",
            significance: "In our era of high-speed digital consumption, Ray's masterpiece teaches us the radical act of patience. It reminds us that dignity is not a function of wealth.",
            artistFact: "Satyajit Ray pawned his wife's jewelry to fund the film. When funds ran dry, the production stopped for a year.",
            layout: "wide",
            dailyContext: "\"The train is coming! The train!\"",
        },
        {
            id: "m13",
            title: "Amelie",
            subtitle: "Jean-Pierre Jeunet, 2001",
            image: "images/amelie.png",
            technicianReview: "A visual delight of green and red hues.",
            soulNote: "Finding magic in the mundane.",
            significance: "A love letter to Paris.",
            artistFact: "To be added.",
            layout: "regular",
            dailyContext: "\"Amelie\"",
        },
        {
            id: "m11",
            title: "Seven Samurai",
            subtitle: "Akira Kurosawa, 1954",
            image: "images/seven_samurai.png",
            technicianReview: "Invented the modern action movie grammar. The use of telephoto lenses captures the chaos of battle.",
            soulNote: "A study of sacrifice and duty.",
            significance: "The ultimate team-up movie.",
            artistFact: "To be added.",
            layout: "regular",
            dailyContext: "\"Seven Samurai\"",
        },
    ],
    music: [
        {
            id: "mu2",
            title: "Sounds of India",
            subtitle: "Ravi Shankar, 1968",
            image: "images/ravi_shankar.png",
            technicianReview: "A pristine capture of complex ragas. The recording balances the sympathetic resonance of the sitar with the punch of the tabla perfectly.",
            soulNote: "Music as meditation. It doesn't follow Western verse-chorus structure but flows like a river.",
            significance: "Indian Classical music demands deep listening, the antidote to the 3-minute pop song.",
            artistFact: "Ravi Shankar famously gave George Harrison sitar lessons.",
            layout: "featured",
            dailyContext: "\"Raga is a form that cannot be separated from the divine.\"",
        },
        {
            id: "mu9",
            title: "Blue",
            subtitle: "Joni Mitchell, 1971",
            image: "images/blue.png",
            technicianReview: "Stripped back to just dulcimer and piano. The microphone placement captures every breath and lip smack.",
            soulNote: "The most honest breakup album ever made. It feels like reading someone's diary.",
            significance: "In a world of curated Instagram lives, 'Blue' dares to be messy and pathetic in the most beautiful way.",
            artistFact: "Mitchell said of this album, 'I felt like I had absolutely no secrets from the world and I couldn't pretend in my life to be strong.'",
            layout: "tall",
            dailyContext: "\"I am on a lonely road and I am traveling.\"",
        },
        {
            id: "mu6",
            title: "Dark Side of the Moon",
            subtitle: "Pink Floyd, 1973",
            image: "images/pink_floyd.png",
            technicianReview: "Alan Parsons used tape loops and physical editing to create seamless transitions. A benchmark for studio engineering.",
            soulNote: "A guided tour through the madness of modern life: time, money, and war.",
            significance: "It remains the ultimate album about the human condition under capitalism.",
            artistFact: "The album remained on the Billboard charts for 741 consecutive weeks—over 14 years.",
            layout: "wide",
            dailyContext: "\"There is no dark side of the moon really.\"",
        },
        {
            id: "m_1768371948_944",
            title: "Getz/Gilberto",
            subtitle: "Stan Getz & João Gilberto, 1964",
            image: "images/getz_gilberto.png",
            technicianReview: "Automatically ingested. A Jazz work by Stan Getz & João Gilberto....",
            soulNote: "To be written by the curator.",
            significance: "A masterpiece from the global archive.",
            artistFact: "To be added.",
            layout: "regular",
            dailyContext: "\"Getz/Gilberto\"",
        },
        {
            id: "mu10",
            title: "Kind of Blue",
            subtitle: "Miles Davis, 1959",
            image: "images/miles.png",
            technicianReview: "Recorded with almost no rehearsal. The tape hiss is part of the atmosphere.",
            soulNote: "Coolness personified. It is the sound of 3 AM in a city that understands you.",
            significance: "It defined 'cool' for the 20th century and taught us that what you don't play is as important as what you do.",
            artistFact: "Miles gave the musicians only sketches of scales and melodies hours before recording.",
            layout: "regular",
            dailyContext: "\"So What.\"",
        },
    ],
    books: [
        {
            id: "b3",
            title: "100 Years of Solitude",
            subtitle: "G.G. Márquez, 1967",
            image: "images/solitude.png",
            technicianReview: "The definitive text of Magical Realism. The prose style mimics the cyclical nature of history.",
            soulNote: "It teaches us that time is not linear, but a circle.",
            significance: "A cautionary tale about the isolation that comes from power.",
            artistFact: "Márquez sold his car and pawned his household appliances to support his family while writing.",
            layout: "featured",
            dailyContext: "\"He really had been through death.\"",
        },
        {
            id: "b1",
            title: "God of Small Things",
            subtitle: "Arundhati Roy, 1997",
            image: "images/small_things.png",
            technicianReview: "A linguistic tour de force. Roy creates her own vocabulary to describe the indescribable.",
            soulNote: "A devastating look at how Big Things crush Small Things.",
            significance: "Roy insists on the complexity of the 'Small Things' in a polarized world.",
            artistFact: "Arundhati Roy trained as an architect before writing the novel.",
            layout: "tall",
            dailyContext: "\"Things can change in a day.\"",
        },
        {
            id: "b_1768371952_583",
            title: "The Alchemist",
            subtitle: "Paulo Coelho, 2015",
            image: "images/the_alchemist.png",
            technicianReview: "Automatically ingested. “To realize one’s destiny is a person’s only obligation.”—from The Alchemist The Alchemist tells the...",
            soulNote: "To be written by the curator.",
            significance: "A masterpiece from the global archive.",
            artistFact: "To be added.",
            layout: "wide",
            dailyContext: "\"The Alchemist\"",
        },
        {
            id: "b5",
            title: "Master and Margarita",
            subtitle: "Mikhail Bulgakov, 1967",
            image: "images/master_margarita.png",
            technicianReview: "A satirical masterpiece written in secret. The tone shifts from slapstick to biblical tragedy.",
            soulNote: "Proof that manuscripts don't burn.",
            significance: "Written under tyranny, it is a testament to the fact that truth cannot be censored forever.",
            artistFact: "Bulgakov burned the first manuscript of the novel in a stove, fearing a police raid.",
            layout: "regular",
            dailyContext: "\"Manuscripts don't burn.\"",
        },
        {
            id: "b8",
            title: "Slaughterhouse-Five",
            subtitle: "Kurt Vonnegut, 1969",
            image: "images/slaughterhouse.png",
            technicianReview: "A non-linear anti-war novel that uses sci-fi tropes to process PTSD.",
            soulNote: "A resigned shrug at the absurdity of death.",
            significance: "It creates a language for trauma that traditional narrative cannot handle.",
            artistFact: "Vonnegut actually survived the firebombing of Dresden as a POW by hiding in a meat locker.",
            layout: "regular",
            dailyContext: "\"So it goes.\"",
        },
    ],
};
